# Generated by Django 4.2.6 on 2023-10-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0004_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgThumb',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
    ]
