# Generated by Django 4.2.6 on 2023-10-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0005_article_imgthumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imgThumb',
            field=models.ImageField(blank=True, null=True, upload_to='media_img'),
        ),
    ]
