# Generated by Django 4.2.6 on 2023-10-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0006_alter_article_imgthumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
