# Generated by Django 4.2.6 on 2023-10-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0008_navigate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigate',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
